Update ru_RU.lang
GTNewHorizons/ForbiddenMagic pull request #3
Opened 2021-05-25 17:02 UTC by Reystlin

Сorrecting grammatical errors, adding new translated text

2021-05-26 09:57 UTC, repo-alt requested changes

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +tc.aspect.desidia=Лень, Нежелание, Промедление
праздность м.б.

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +item.Wand.profane.rod=Оскверненный
Мне кажется в оригинале не имелось в виду profane как profanity, а имелось в виду что непрофессиональный, профанный, сделан на коленке неспециалистами

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +death.attack.dragonwrack=%1$s не стал сопротивляться смертельным ранам
Просто погиб от смертельной раны

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +forbidden.research_page.NETHERSHARDS.2b=Эти кристаллы пронизаны различными пороками и имеют множество применений для бессовестных тауматургов.<BR>Есть шесть типов Адских осколков и каждый представляе
"представляется собой", так вообще нельзя сказать
attuned, ну "соответствует" м.б.

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +forbidden.research_page.RINGFOOD.1=Люди продолжают ругать Вас. Они говорят, что нельзя есть печенье целый день или что "насыщение работает иначе". Что ж, раньше Вам приходилось выслушивать этих скепт
порядок слов?: "делает её питательнее которую Вы употребляете"

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +forbidden.research_page.TAINTSHOVEL.1=Иногда, самый простой способ убрать пятна заражения - просто физически убрать их.<BR><BR>Укрепляя таум-лопату серебряной древесиной и осколками порядка, Вы созда
копать "через" что-то? просто копать

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +forbidden.research_page.TAINTSTONE.1=Зараженные Земли не такие уж и дружелюбные, и не кажутся безопасными. Заражение жадно распространяется и ползет все быстрее по поверхности, и в конце концов покры
угрозы "для", не "к"
смешивание -> смешав
в конце фразы кажется лучше "но..."

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +forbidden.research_name.ROD_profane=Оскверненный жезл
аналогично выше

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +forbidden.research_text.ROD_profane=На волоске от...
Буквально имелось виду "осталось только расписаться", но я не помню контекста так что м.б. и ок

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +forbidden.research_name.CAP_vinteum=Наконечники Винтеума
Vinteum это вроде как материал?

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +forbidden.research_text.PRIMEWELL=Заслуженное хвастовство!
"Право похвастать", м.б. как вариант

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +forbidden.research_page.PRIMEWELL.1=Вы познали вещи, которые не придут на ум обычному человеку, вы видели вещи, которые люди и представить не могли, вы были в местах, который лежат за гранью человече
опечатка "кооторые"

2021-05-26 09:57 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +forbidden.research_page.EUCLIDAISY.1=Эфирная эссенция, является чрезвычайно полезным источником эссенции и очень важным ингредиентом для соли тауматурга. К сожалению, её очень трудно найти. Но даже н
может поправить тут заодно разгром на разрушение

2021-05-26 10:32 UTC, repo-alt commented on src/main/resources/assets/forbidden/lang/ru_RU.lang
> +item.Wand.profane.rod=Оскверненный
Ближе всего по оттенкам смыслов будет видимо "поганый", "скверный", потому что там схожее развитие смыслов, от ритуальной нечистоты к бытовому ругательству

2021-06-03 09:35 UTC, Dream-Master commented
@Reystlin can you add this suggested changes ?

2021-06-03 17:37 UTC, Dream-Master commented
@repo-alt no all done or still a few are missing?

2021-06-03 17:44 UTC, Dream-Master commented
@Reystlin did you catch all ?

2021-06-03 17:52 UTC, Prometheus0000 commented
Wasn't this the mod that had problems with items disappearing if you build from the repo? Was that resolved yet? Because I don't think a russian translation is worth breaking a bunch of stuff if it isn't fixed yet. It could be a different mod though.

2021-06-03 18:04 UTC, repo-alt approved these changes

2021-06-03 18:06 UTC, merged